"""alert_rules + alerts + extraction alert_status

Revision ID: 5d89a35fc658
Revises: 75da6ec97ef8
Create Date: 2026-07-07 00:51:18.210830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d89a35fc658'
down_revision: Union[str, Sequence[str], None] = '75da6ec97ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('webhook_status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extraction_id', 'rule_id', name='uq_alerts_extraction_rule')
    )
    op.create_index(op.f('ix_alerts_extraction_id'), 'alerts', ['extraction_id'], unique=False)
    op.add_column('extractions', sa.Column('alert_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('extractions', sa.Column('alert_claimed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Backfill: existing extractions should not retroactively fire alerts.
    # New rows still default to 'pending' via the server_default above / model default.
    op.execute("UPDATE extractions SET alert_status = 'done'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extractions', 'alert_claimed_at')
    op.drop_column('extractions', 'alert_status')
    op.drop_index(op.f('ix_alerts_extraction_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
