"""add discovery columns to figures and sources

Revision ID: 75da6ec97ef8
Revises: 8401b3d9fee9
Create Date: 2026-07-06 10:32:26.507849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75da6ec97ef8'
down_revision: Union[str, Sequence[str], None] = '8401b3d9fee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('figures', sa.Column('wikidata_id', sa.String(length=32), nullable=True))
    op.add_column('figures', sa.Column('discovery_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('figures', sa.Column('discovery_claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('figures', sa.Column('discovery_error', sa.Text(), nullable=True))
    op.create_index(op.f('ix_figures_wikidata_id'), 'figures', ['wikidata_id'], unique=False)
    op.add_column('sources', sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
    op.add_column('sources', sa.Column('verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('sources', sa.Column('discovery_confidence', sa.Float(), nullable=True))
    op.add_column('sources', sa.Column('discovery_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'discovery_meta')
    op.drop_column('sources', 'discovery_confidence')
    op.drop_column('sources', 'verified')
    op.drop_column('sources', 'status')
    op.drop_index(op.f('ix_figures_wikidata_id'), table_name='figures')
    op.drop_column('figures', 'discovery_error')
    op.drop_column('figures', 'discovery_claimed_at')
    op.drop_column('figures', 'discovery_status')
    op.drop_column('figures', 'wikidata_id')
    # ### end Alembic commands ###
