"""create relevance_labels, extraction_labels, dspy_programs, eval_runs

Revision ID: 8401b3d9fee9
Revises: aa1236c0980c
Create Date: 2026-07-05 21:08:38.907231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8401b3d9fee9'
down_revision: Union[str, Sequence[str], None] = 'aa1236c0980c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dspy_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('artifact', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('holdout_score', sa.Float(), nullable=True),
    sa.Column('is_champion', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'version', name='uq_dspy_programs_module_version')
    )
    op.create_index(op.f('ix_dspy_programs_module'), 'dspy_programs', ['module'], unique=False)
    op.create_table('eval_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('dspy_program_id', sa.Integer(), nullable=True),
    sa.Column('split', sa.String(length=10), nullable=False),
    sa.Column('metric', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dspy_program_id'], ['dspy_programs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('magnitude', sa.String(length=20), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('split', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_labels_statement_id'), 'extraction_labels', ['statement_id'], unique=True)
    op.create_table('relevance_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('is_relevant', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('split', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relevance_labels_statement_id'), 'relevance_labels', ['statement_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relevance_labels_statement_id'), table_name='relevance_labels')
    op.drop_table('relevance_labels')
    op.drop_index(op.f('ix_extraction_labels_statement_id'), table_name='extraction_labels')
    op.drop_table('extraction_labels')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_dspy_programs_module'), table_name='dspy_programs')
    op.drop_table('dspy_programs')
    # ### end Alembic commands ###
