"""create resolutions, entity_symbols, impacts

Revision ID: aa1236c0980c
Revises: dfd2c3bc1dd7
Create Date: 2026-07-05 13:02:26.000326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1236c0980c'
down_revision: Union[str, Sequence[str], None] = 'dfd2c3bc1dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_entity', sa.String(length=300), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('asset_class', sa.String(length=20), nullable=True),
    sa.Column('measurable', sa.Boolean(), nullable=False),
    sa.Column('instrument_name', sa.String(length=300), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_entity')
    )
    op.create_table('resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=300), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('asset_class', sa.String(length=20), nullable=True),
    sa.Column('measurable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolutions_extraction_id'), 'resolutions', ['extraction_id'], unique=False)
    op.create_table('impacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resolution_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('window', sa.String(length=10), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price_t0', sa.Float(), nullable=True),
    sa.Column('price_after', sa.Float(), nullable=True),
    sa.Column('pct_move', sa.Float(), nullable=True),
    sa.Column('volume_spike', sa.Float(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resolution_id', 'window', name='uq_impacts_resolution_window')
    )
    op.create_index(op.f('ix_impacts_due_at'), 'impacts', ['due_at'], unique=False)
    op.create_index(op.f('ix_impacts_resolution_id'), 'impacts', ['resolution_id'], unique=False)
    op.create_index(op.f('ix_impacts_status'), 'impacts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_impacts_status'), table_name='impacts')
    op.drop_index(op.f('ix_impacts_resolution_id'), table_name='impacts')
    op.drop_index(op.f('ix_impacts_due_at'), table_name='impacts')
    op.drop_table('impacts')
    op.drop_index(op.f('ix_resolutions_extraction_id'), table_name='resolutions')
    op.drop_table('resolutions')
    op.drop_table('entity_symbols')
    # ### end Alembic commands ###
